export { default as GTPressuraBold } from "./GTPressuraBold.ttf"
export { default as GTPressuraBoldItalic } from "./GTPressuraBoldItalic.ttf"
export { default as GTPressuraRegular } from "./GTPressuraRegular.ttf"
export { default as GTPressuraRegularItalic } from "./GTPressuraRegularItalic.ttf"
export { default as MerriWeatherRegular } from "./MerriweatherRegular.ttf"
export { default as MerriWeatherItalic } from "./MerriweatherItalic.ttf"
